enyo.depends(
	"mixins/",
	"SearchForm.js",
	"TableRowList.js",
	"EditableTable.js",
	"InputDecorator.js",
	"TextAreaDecorator.js",
	"FormDecorator.js",
	"DropdownList.js",
	"DropdownListDecorator.js"
);