enyo.depends(
	"Dialog.js",
	"AlertDialog.js",
	"ConfirmDialog.js",
	"SpinnerDialog.js",
	"NormalDialog.js",
	"HtmlEditor.js",
	"IframeDialog.js",
	"LoginDialog.js",
	"NormalLoginDialog.js",
	"TreeNodeDialog.js"
);